apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: transaction
  template:
    metadata:
      labels:
        app: transaction
    spec:
      containers:
      - name: transaction
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 3001