apiVersion: apps/v1
kind: Deployment
metadata:
metadata:
  name: legacy-service
  namespace: uat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: legacy-service
  template:
    metadata:
      labels:
        app: legacy-service
    spec:
      containers:
      - name: legacy-service
        image: k8s-gitops-platform-legacy-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000